<template><div><h1 id="performance-playbook" tabindex="-1"><a class="header-anchor" href="#performance-playbook"><span>Performance Playbook</span></a></h1>
<p>Fast media selection requires careful attention to both backend queries and frontend payloads.<br>
This page lists the optimizations implemented in the package and what you can do to keep things snappy.</p>
<h2 id="avoiding-n-1-queries" tabindex="-1"><a class="header-anchor" href="#avoiding-n-1-queries"><span>Avoiding N+1 queries</span></a></h2>
<h3 id="looping-through-posts-with-eager-load" tabindex="-1"><a class="header-anchor" href="#looping-through-posts-with-eager-load"><span>Looping through posts with eager-load</span></a></h3>
<div class="language-php line-numbers-mode" data-highlighter="prismjs" data-ext="php"><pre v-pre><code class="language-php"><span class="line"><span class="token variable">$posts</span> <span class="token operator">=</span> <span class="token class-name static-context">Post</span><span class="token operator">::</span><span class="token function">query</span><span class="token punctuation">(</span><span class="token punctuation">)</span></span>
<span class="line">    <span class="token operator">-></span><span class="token function">withMediaCollection</span><span class="token punctuation">(</span><span class="token string single-quoted-string">'gallery'</span><span class="token punctuation">)</span></span>
<span class="line">    <span class="token operator">-></span><span class="token function">latest</span><span class="token punctuation">(</span><span class="token punctuation">)</span></span>
<span class="line">    <span class="token operator">-></span><span class="token function">take</span><span class="token punctuation">(</span><span class="token number">12</span><span class="token punctuation">)</span></span>
<span class="line">    <span class="token operator">-></span><span class="token function">get</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line"></span>
<span class="line"><span class="token keyword">foreach</span> <span class="token punctuation">(</span><span class="token variable">$posts</span> <span class="token keyword">as</span> <span class="token variable">$post</span><span class="token punctuation">)</span> <span class="token punctuation">{</span></span>
<span class="line">    <span class="token variable">$images</span> <span class="token operator">=</span> <span class="token variable">$post</span><span class="token operator">-></span><span class="token function">getMedia</span><span class="token punctuation">(</span><span class="token string single-quoted-string">'gallery'</span><span class="token punctuation">)</span><span class="token punctuation">;</span>    <span class="token comment">// no additional queries</span></span>
<span class="line">    <span class="token variable">$firstUrl</span> <span class="token operator">=</span> <span class="token variable">$post</span><span class="token operator">-></span><span class="token function">getMediaUrl</span><span class="token punctuation">(</span><span class="token string single-quoted-string">'gallery'</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line"></span>
<span class="line">    <span class="token comment">// render a thumbnail list or hero image</span></span>
<span class="line"><span class="token punctuation">}</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><ul>
<li>The <code v-pre>HasMediaSelector</code> trait respects eager-loaded relationships, so the loop above does not trigger extra DB hits.</li>
<li><code v-pre>getMedia()</code> checks <code v-pre>relationLoaded('media')</code> to reuse the in-memory collection.</li>
<li><code v-pre>getMediaUrls()</code> and <code v-pre>getMediaUrl()</code> leverage the cached relation when available.</li>
<li>Pass a callback as the second parameter of <code v-pre>withMediaCollection()</code> to order or further constrain the eager-loaded relation.</li>
</ul>
<h2 id="query-scopes" tabindex="-1"><a class="header-anchor" href="#query-scopes"><span>Query scopes</span></a></h2>
<h3 id="filtering-media-in-bulk-jobs" tabindex="-1"><a class="header-anchor" href="#filtering-media-in-bulk-jobs"><span>Filtering media in bulk jobs</span></a></h3>
<div class="language-php line-numbers-mode" data-highlighter="prismjs" data-ext="php"><pre v-pre><code class="language-php"><span class="line"><span class="token variable">$expired</span> <span class="token operator">=</span> <span class="token class-name static-context">Media</span><span class="token operator">::</span><span class="token function">query</span><span class="token punctuation">(</span><span class="token punctuation">)</span></span>
<span class="line">    <span class="token operator">-></span><span class="token function">forDisk</span><span class="token punctuation">(</span><span class="token string single-quoted-string">'public'</span><span class="token punctuation">)</span></span>
<span class="line">    <span class="token operator">-></span><span class="token function">forCollection</span><span class="token punctuation">(</span><span class="token string single-quoted-string">'tmp-uploads'</span><span class="token punctuation">)</span></span>
<span class="line">    <span class="token operator">-></span><span class="token function">whereDate</span><span class="token punctuation">(</span><span class="token string single-quoted-string">'created_at'</span><span class="token punctuation">,</span> <span class="token string single-quoted-string">'&lt;'</span><span class="token punctuation">,</span> <span class="token function">now</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token operator">-></span><span class="token function">subDay</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">)</span></span>
<span class="line">    <span class="token operator">-></span><span class="token function">pluck</span><span class="token punctuation">(</span><span class="token string single-quoted-string">'id'</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line"></span>
<span class="line"><span class="token class-name static-context">Media</span><span class="token operator">::</span><span class="token function">whereIn</span><span class="token punctuation">(</span><span class="token string single-quoted-string">'id'</span><span class="token punctuation">,</span> <span class="token variable">$expired</span><span class="token punctuation">)</span><span class="token operator">-></span><span class="token function">delete</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>Combine scope helpers with Laravel scheduler jobs to keep temporary collections small.</p>
<h2 id="caching-cdns" tabindex="-1"><a class="header-anchor" href="#caching-cdns"><span>Caching &amp; CDNs</span></a></h2>
<div class="language-php line-numbers-mode" data-highlighter="prismjs" data-ext="php"><pre v-pre><code class="language-php"><span class="line"><span class="token comment">// config/filesystems.php</span></span>
<span class="line"><span class="token string single-quoted-string">'disks'</span> <span class="token operator">=></span> <span class="token punctuation">[</span></span>
<span class="line">    <span class="token string single-quoted-string">'media_cdn'</span> <span class="token operator">=></span> <span class="token punctuation">[</span></span>
<span class="line">        <span class="token string single-quoted-string">'driver'</span> <span class="token operator">=></span> <span class="token string single-quoted-string">'s3'</span><span class="token punctuation">,</span></span>
<span class="line">        <span class="token string single-quoted-string">'key'</span> <span class="token operator">=></span> <span class="token function">env</span><span class="token punctuation">(</span><span class="token string single-quoted-string">'AWS_ACCESS_KEY_ID'</span><span class="token punctuation">)</span><span class="token punctuation">,</span></span>
<span class="line">        <span class="token string single-quoted-string">'secret'</span> <span class="token operator">=></span> <span class="token function">env</span><span class="token punctuation">(</span><span class="token string single-quoted-string">'AWS_SECRET_ACCESS_KEY'</span><span class="token punctuation">)</span><span class="token punctuation">,</span></span>
<span class="line">        <span class="token string single-quoted-string">'region'</span> <span class="token operator">=></span> <span class="token function">env</span><span class="token punctuation">(</span><span class="token string single-quoted-string">'AWS_DEFAULT_REGION'</span><span class="token punctuation">)</span><span class="token punctuation">,</span></span>
<span class="line">        <span class="token string single-quoted-string">'bucket'</span> <span class="token operator">=></span> <span class="token function">env</span><span class="token punctuation">(</span><span class="token string single-quoted-string">'AWS_BUCKET'</span><span class="token punctuation">)</span><span class="token punctuation">,</span></span>
<span class="line">        <span class="token string single-quoted-string">'url'</span> <span class="token operator">=></span> <span class="token function">env</span><span class="token punctuation">(</span><span class="token string single-quoted-string">'AWS_URL'</span><span class="token punctuation">)</span><span class="token punctuation">,</span> <span class="token comment">// CloudFront or custom CDN domain</span></span>
<span class="line">    <span class="token punctuation">]</span><span class="token punctuation">,</span></span>
<span class="line"><span class="token punctuation">]</span><span class="token punctuation">,</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><div class="language-php line-numbers-mode" data-highlighter="prismjs" data-ext="php"><pre v-pre><code class="language-php"><span class="line"><span class="token comment">// config/media-selector.php</span></span>
<span class="line"><span class="token string single-quoted-string">'disk'</span> <span class="token operator">=></span> <span class="token function">env</span><span class="token punctuation">(</span><span class="token string single-quoted-string">'MEDIA_SELECTOR_DISK'</span><span class="token punctuation">,</span> <span class="token string single-quoted-string">'media_cdn'</span><span class="token punctuation">)</span><span class="token punctuation">,</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div></div></div><ul>
<li>The media selector reads URLs from the configured disk; pointing the disk at a CDN ensures generated links are cacheable.</li>
<li>For image-heavy galleries, store pre-generated thumbnails in a secondary collection (e.g. <code v-pre>gallery-thumbs</code>) and reference that in your app UI.</li>
</ul>
<h2 id="thumbnail-rendering" tabindex="-1"><a class="header-anchor" href="#thumbnail-rendering"><span>Thumbnail rendering</span></a></h2>
<div class="language-php line-numbers-mode" data-highlighter="prismjs" data-ext="php"><pre v-pre><code class="language-php"><span class="line"><span class="token comment">// config/media-selector.php</span></span>
<span class="line"><span class="token string single-quoted-string">'preview_mimes'</span> <span class="token operator">=></span> <span class="token punctuation">[</span></span>
<span class="line">    <span class="token string single-quoted-string">'image/jpeg'</span><span class="token punctuation">,</span></span>
<span class="line">    <span class="token string single-quoted-string">'image/png'</span><span class="token punctuation">,</span></span>
<span class="line">    <span class="token string single-quoted-string">'image/webp'</span><span class="token punctuation">,</span></span>
<span class="line"><span class="token punctuation">]</span><span class="token punctuation">,</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><div class="language-php line-numbers-mode" data-highlighter="prismjs" data-ext="php"><pre v-pre><code class="language-php"><span class="line"><span class="token operator">&lt;</span>livewire<span class="token punctuation">:</span>media<span class="token operator">-</span>selector</span>
<span class="line">    wire<span class="token punctuation">:</span>model<span class="token operator">=</span><span class="token string double-quoted-string">"gallery"</span></span>
<span class="line">    collection<span class="token operator">=</span><span class="token string double-quoted-string">"gallery"</span></span>
<span class="line">    <span class="token punctuation">:</span><span class="token keyword">require</span><span class="token operator">-</span>width<span class="token operator">=</span><span class="token string double-quoted-string">"800"</span></span>
<span class="line">    <span class="token punctuation">:</span><span class="token keyword">require</span><span class="token operator">-</span>height<span class="token operator">=</span><span class="token string double-quoted-string">"600"</span></span>
<span class="line"><span class="token operator">/</span><span class="token operator">></span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><ul>
<li>Constrain previewable MIME types to avoid rendering heavy video assets in the grid.</li>
<li>Enforce dimensions for uploads when you need consistent aspect ratios across the UI.</li>
</ul>
<h2 id="upload-throughput" tabindex="-1"><a class="header-anchor" href="#upload-throughput"><span>Upload throughput</span></a></h2>
<h3 id="large-file-uploads-component-snippet" tabindex="-1"><a class="header-anchor" href="#large-file-uploads-component-snippet"><span>Large file uploads component snippet</span></a></h3>
<div class="language-blade line-numbers-mode" data-highlighter="prismjs" data-ext="blade"><pre v-pre><code class="language-blade"><span class="line">&lt;livewire:media-selector</span>
<span class="line">    wire:model=&quot;videos&quot;</span>
<span class="line">    collection=&quot;course-videos&quot;</span>
<span class="line">    :multiple=&quot;true&quot;</span>
<span class="line">    :max-upload-kb=&quot;102400&quot;   {{-- 100 MB --}}</span>
<span class="line">    mimes='[&quot;video/mp4&quot;,&quot;video/webm&quot;]'</span>
<span class="line">/&gt;</span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><ul>
<li>Leverage Livewire’s chunked uploads (handled internally by <code v-pre>HandlesUploads</code>) for large files.</li>
<li>Surface limits in UI copy so users understand the allowed file size and type boundaries.</li>
</ul>
<h2 id="database-hygiene" tabindex="-1"><a class="header-anchor" href="#database-hygiene"><span>Database hygiene</span></a></h2>
<h3 id="cleaning-orphaned-pivots" tabindex="-1"><a class="header-anchor" href="#cleaning-orphaned-pivots"><span>Cleaning orphaned pivots</span></a></h3>
<div class="language-php line-numbers-mode" data-highlighter="prismjs" data-ext="php"><pre v-pre><code class="language-php"><span class="line"><span class="token class-name static-context">Schedule</span><span class="token operator">::</span><span class="token function">command</span><span class="token punctuation">(</span><span class="token string single-quoted-string">'media-selector:prune-temp'</span><span class="token punctuation">)</span></span>
<span class="line">    <span class="token operator">-></span><span class="token function">daily</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div></div></div><div class="language-php line-numbers-mode" data-highlighter="prismjs" data-ext="php"><pre v-pre><code class="language-php"><span class="line"><span class="token class-name static-context">Artisan</span><span class="token operator">::</span><span class="token function">command</span><span class="token punctuation">(</span><span class="token string single-quoted-string">'media-selector:prune-temp'</span><span class="token punctuation">,</span> <span class="token keyword">function</span> <span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token punctuation">{</span></span>
<span class="line">    <span class="token variable">$count</span> <span class="token operator">=</span> <span class="token class-name static-context">DB</span><span class="token operator">::</span><span class="token function">table</span><span class="token punctuation">(</span><span class="token string single-quoted-string">'media_selector_mediables'</span><span class="token punctuation">)</span></span>
<span class="line">        <span class="token operator">-></span><span class="token function">whereNotIn</span><span class="token punctuation">(</span><span class="token string single-quoted-string">'media_id'</span><span class="token punctuation">,</span> <span class="token class-name static-context">Media</span><span class="token operator">::</span><span class="token function">query</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token operator">-></span><span class="token function">select</span><span class="token punctuation">(</span><span class="token string single-quoted-string">'id'</span><span class="token punctuation">)</span><span class="token punctuation">)</span></span>
<span class="line">        <span class="token operator">-></span><span class="token function">delete</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line"></span>
<span class="line">    <span class="token variable">$this</span><span class="token operator">-></span><span class="token function">info</span><span class="token punctuation">(</span><span class="token string double-quoted-string">"Removed <span class="token interpolation"><span class="token punctuation">{</span><span class="token variable">$count</span><span class="token punctuation">}</span></span> orphaned pivot rows."</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line"><span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><ul>
<li><code v-pre>syncMedia()</code> already removes stale attachments when updating a single model; scheduled jobs keep global tables tidy.</li>
<li>Add DB indexes on <code v-pre>media_selector_media.collection</code>, <code v-pre>media_selector_media.disk</code>, and <code v-pre>media_selector_mediables.media_id</code> for large datasets.</li>
</ul>
</div></template>


