<template><div><h1 id="testing-recipes" tabindex="-1"><a class="header-anchor" href="#testing-recipes"><span>Testing Recipes</span></a></h1>
<p>The package ships with Pest-powered feature tests.<br>
Use these examples to test your own integrations and keep regressions out of production.</p>
<h2 id="faking-storage" tabindex="-1"><a class="header-anchor" href="#faking-storage"><span>Faking storage</span></a></h2>
<div class="language-php line-numbers-mode" data-highlighter="prismjs" data-ext="php"><pre v-pre><code class="language-php"><span class="line"><span class="token class-name static-context">Storage</span><span class="token operator">::</span><span class="token function">fake</span><span class="token punctuation">(</span><span class="token string single-quoted-string">'public'</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line"></span>
<span class="line"><span class="token variable">$media</span> <span class="token operator">=</span> <span class="token class-name static-context">Media</span><span class="token operator">::</span><span class="token function">create</span><span class="token punctuation">(</span><span class="token punctuation">[</span></span>
<span class="line">    <span class="token string single-quoted-string">'disk'</span> <span class="token operator">=></span> <span class="token string single-quoted-string">'public'</span><span class="token punctuation">,</span></span>
<span class="line">    <span class="token string single-quoted-string">'path'</span> <span class="token operator">=></span> <span class="token string single-quoted-string">'media/example.jpg'</span><span class="token punctuation">,</span></span>
<span class="line">    <span class="token string single-quoted-string">'filename'</span> <span class="token operator">=></span> <span class="token string single-quoted-string">'example.jpg'</span><span class="token punctuation">,</span></span>
<span class="line">    <span class="token string single-quoted-string">'collection'</span> <span class="token operator">=></span> <span class="token string single-quoted-string">'gallery'</span><span class="token punctuation">,</span></span>
<span class="line">    <span class="token string single-quoted-string">'mime'</span> <span class="token operator">=></span> <span class="token string single-quoted-string">'image/jpeg'</span><span class="token punctuation">,</span></span>
<span class="line"><span class="token punctuation">]</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line"></span>
<span class="line"><span class="token function">expect</span><span class="token punctuation">(</span><span class="token class-name static-context">Storage</span><span class="token operator">::</span><span class="token function">disk</span><span class="token punctuation">(</span><span class="token string single-quoted-string">'public'</span><span class="token punctuation">)</span><span class="token operator">-></span><span class="token function">exists</span><span class="token punctuation">(</span><span class="token variable">$media</span><span class="token operator">-></span><span class="token property">path</span><span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token operator">-></span><span class="token function">toBeTrue</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h2 id="livewire-component-tests" tabindex="-1"><a class="header-anchor" href="#livewire-component-tests"><span>Livewire component tests</span></a></h2>
<div class="language-php line-numbers-mode" data-highlighter="prismjs" data-ext="php"><pre v-pre><code class="language-php"><span class="line"><span class="token class-name static-context">Livewire</span><span class="token operator">::</span><span class="token function">test</span><span class="token punctuation">(</span><span class="token class-name static-context">MediaSelector</span><span class="token operator">::</span><span class="token keyword">class</span><span class="token punctuation">)</span></span>
<span class="line">    <span class="token operator">-></span><span class="token function">call</span><span class="token punctuation">(</span><span class="token string single-quoted-string">'openModal'</span><span class="token punctuation">)</span></span>
<span class="line">    <span class="token operator">-></span><span class="token function">assertSet</span><span class="token punctuation">(</span><span class="token string single-quoted-string">'showModal'</span><span class="token punctuation">,</span> <span class="token constant boolean">true</span><span class="token punctuation">)</span></span>
<span class="line">    <span class="token operator">-></span><span class="token function">set</span><span class="token punctuation">(</span><span class="token string single-quoted-string">'selectedIds'</span><span class="token punctuation">,</span> <span class="token punctuation">[</span><span class="token variable">$media</span><span class="token operator">-></span><span class="token property">id</span><span class="token punctuation">]</span><span class="token punctuation">)</span></span>
<span class="line">    <span class="token operator">-></span><span class="token function">call</span><span class="token punctuation">(</span><span class="token string single-quoted-string">'closeModal'</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h2 id="trait-helpers" tabindex="-1"><a class="header-anchor" href="#trait-helpers"><span>Trait helpers</span></a></h2>
<div class="language-php line-numbers-mode" data-highlighter="prismjs" data-ext="php"><pre v-pre><code class="language-php"><span class="line"><span class="token variable">$post</span> <span class="token operator">=</span> <span class="token class-name static-context">TestHasMediaModel</span><span class="token operator">::</span><span class="token function">create</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line"><span class="token variable">$post</span><span class="token operator">-></span><span class="token function">attachMedia</span><span class="token punctuation">(</span><span class="token punctuation">[</span><span class="token punctuation">[</span><span class="token string single-quoted-string">'id'</span> <span class="token operator">=></span> <span class="token variable">$media</span><span class="token operator">-></span><span class="token property">id</span><span class="token punctuation">]</span><span class="token punctuation">]</span><span class="token punctuation">,</span> <span class="token string single-quoted-string">'gallery'</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line"></span>
<span class="line"><span class="token function">expect</span><span class="token punctuation">(</span><span class="token variable">$post</span><span class="token operator">-></span><span class="token function">getMediaUrl</span><span class="token punctuation">(</span><span class="token string single-quoted-string">'gallery'</span><span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token operator">-></span><span class="token function">toEndWith</span><span class="token punctuation">(</span><span class="token string single-quoted-string">'example.jpg'</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h3 id="assertions" tabindex="-1"><a class="header-anchor" href="#assertions"><span>Assertions</span></a></h3>
<ul>
<li><code v-pre>assertSee()</code> for modal labels and translated strings.</li>
<li><code v-pre>assertHasErrors()</code> when validating uploads.</li>
<li><code v-pre>assertSet()</code> to verify Livewire property mutations.</li>
</ul>
<p>Run the entire suite with:</p>
<div class="language-bash line-numbers-mode" data-highlighter="prismjs" data-ext="sh"><pre v-pre><code class="language-bash"><span class="line"><span class="token function">composer</span> <span class="token builtin class-name">test</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div></div></div></div></template>


